name: code-checks

on:
  pull_request: {}
  push:
    branches:
      - "**"

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  gosec:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@0.36.0
    with:
      install-go: true
      go-version: "1.20.4"
      lint-commands: |
        make bootstrap-tools
        make lintsec

  golint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@0.36.0
    with:
      install-go: true
      go-version: "1.20.4"
      lint-commands: |
        make bootstrap-tools
        make lint
