name: test

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  test:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.35.0
    with:
      install-go: true
      go-version: "1.20.4"
      test-commands: make test
      report-coverage: true
      coverage-file: cover.out
